class Array
  # Sorts the items by "natural ordering" using a set of keys generated by mapping the values through the given
  # block. For example, ['11', '2', '1'].natural_sort_by { |i| i } == ['1', '2', '11'],
  # while ['11', '2', '1'].sort_by { |i| i } == ['1', '11', '2'].
  def natural_sort_by
    sort_by do |e|
      ws = (yield e).scan(/[^\d]+|\d+/).map { |w| w.match(/^\d/) ? w.to_i : w }  # an array of alternating strings and integers
      ws[0].is_a?(String) ? ws : ([''] + ws)  # make the first element always be a string
    end
  end
end
